### PR TITLE
feat(tags): Add tags

### PR DESCRIPTION
**Pull request by astra137**

### CODE REVIEW

**Comment by puregarlic** [comment]
@maccelerated, great work. A couple changes would be great:
+ Change the metadata section into an inline form for item labels
+ Prevent users from adding a second tag with the same name (pop a [Message](http://element.eleme.io/#/en-US/component/message))
+ Tweak the tag [transitions](http://element.eleme.io/#/en-US/component/transition)
+ Remove the name and ID from the tag popover, that info doesn't need to be displayed.

**Comment by astra137** [comment]
Using a different transition for tags seemed like it was going to take more time than I wanted to invest tonight. Since nothing else on that view transitions between *elements*, I figure no transition is fine on tags too. I'm sorry I didn't launch b0f6dbf in ∆ now. If you want me to, I'll look into my build issues further.

**Comment by puregarlic** [comment]
If you try a ∆ now deployment, do you run into #39?

**Comment by maccelerated** [comment]
https://devise-feat-tags-gmaycwpigp.now.sh

**Comment by astra137** [comment]
Removing elements is broken after the state changes I made. I will fix and commit.

**Comment by astra137** [comment]
https://devise-feat-tags-eydlfesepi.now.sh

**Review by puregarlic — APPROVED** [review]
I think this will do.

**Pull request merged**
