### PR TITLE
feat/markdown

### PR DESCRIPTION
**Pull request by astra137**
Add a markdown editor to replace the plain textarea.

### CODE REVIEW

**Comment by astra137** [comment]
To be honest, I'm not sure what to do about the broken code editor thing. It works fine otherwise.

**Comment by puregarlic** [comment]
Is there any way that we can disable it?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by astra137** [comment]
`simplemde` is beautiful.

**Review by puregarlic — APPROVED** [review]
Awesome!

**Pull request merged**
